### ISSUE TITLE
Single Player 1.12 crash on startup

### ISSUE THREAD

**Issue by Zygus42** [gbui/SimpleTreeDrops#4]
SimpleTreeDrops-1.12-1.0.3
forge-1.12-14.21.1.2387-installer-win

Some kind of issue with loot tables:
[latest.log.zip](https://github.com/gbui/SimpleTreeDrops/files/1118873/latest.log.zip)

**Comment by gbui** [comment]
Try this: https://minecraft.curseforge.com/projects/simple-tree-drops/files/2445664
